In [1]:
import arcpy
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\Bhakt\Desktop\TaxWebApp\cityrecords.txt", sep="|")
df.head(10)

,Year,Account_Number,Record_Type,Name,Address,City,State
0,2020,151,AAAA,City of Fort Worth,200 Texas St,Fort Worth,TX
1,2020,152,AAAA,City of Fort Worth,204 Texas St,Fort Worth,TX
2,2020,161,AAAA,City of Fort Worth,201 Texas St,Fort Worth,TX
3,2018,162,AAAA,City of Fort Worth,220 Texas St,Fort Worth,TX
4,2020,154,AAAA,City of Fort Worth,200 Texas St,Fort Worth,TX
5,2020,158,AAAA,City of Fort Worth,304 Texas St,Fort Worth,TX
6,2020,157,AAAA,City of Fort Worth,401 Texas St,Fort Worth,TX
7,2020,171,AAAA,City of Fort Worth,601 Texas St,Fort Worth,TX
8,2018,178,AAAA,City of Fort Worth,250 Texas St,Fort Worth,TX
9,2020,181,AAAA,City of Fort Worth,267 Texas St,Fort Worth,TX